- name: play backend
  hosts: app
  tags:
  - be-pre-build
  tasks:
  - name: go is installed
    import_role:
      name: abdennour.golang
    vars:
      golang_version: "1.14"
      golang_packages:
      - github.com/gorilla/mux
      - go.mongodb.org/mongo-driver/mongo
      golang_users:
      - "{{ ansible_ssh_user }}"
    become: yes
  
- name: play backend
  hosts: app
  become: yes
  tags:
  - be-build
  tasks:
  - name: workspace build exists
    file:
      path: /opt/build_dir
      state: directory
  - name: git checkout
    git:
      repo: https://github.com/kubernetes-tn/go-to-do-app.git
      dest: /opt/build_dir/go-to-do-app
  - name: go build
    shell: . /etc/profile;go build -o /tmp/todo
    args:
      chdir: /opt/build_dir/go-to-do-app/server

- name: play backend
  hosts: app
  become: yes
  tags:
  - be-deploy
  tasks: []
