- name: play backend
  hosts: app
  tags:
  - be-pre-build
  tasks:
  - name: go is installed
    import_role:
      name: abdennour.golang
    vars:
      golang_version: "1.14"
      golang_packages:
      - github.com/gorilla/mux
      - go.mongodb.org/mongo-driver/mongo
      golang_users:
      - "{{ ansible_ssh_user }}"
    become: yes
  
- name: play backend
  hosts: app
  become: yes
  vars:
    be_build_workspace: /opt/build_dir
    be_repo_url: https://github.com/kubernetes-tn/go-to-do-app.git
    be_repo_name: go-to-do-app
  tags:
  - be-build
  tasks:
  - name: workspace build exists
    file:
      path: "{{ be_build_workspace }}"
      state: directory
  - name: git checkout
    git:
      repo: "{{ be_repo_url }}"
      dest: "{{ be_build_workspace }}/{{ be_repo_name }}"
  - name: go build
    shell: . /etc/profile;go build -o /tmp/todo
    args:
      chdir: "{{ be_build_workspace }}/{{ be_repo_name }}/server"

- name: play backend
  hosts: app
  become: yes
  tags:
  - be-deploy
  tasks: []
